import type { PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import Nav from '@web/components/Nav'

import '@web/css/global.css'

export const metadata: Metadata = {
    title: 'CFCC LEADERBOARD',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
            <body>
            {children}
            </body>
        </html>
    )
}
